# Generated by Django 5.0.1 on 2024-02-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaaa', '0004_dispositivomedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivomedicao',
            name='velocidade',
            field=models.FloatField(default=0.0),
        ),
    ]
