# Generated by Django 5.0.1 on 2024-02-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaaa', '0005_dispositivomedicao_velocidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicaoVelocidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('velocidade', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='DispositivoMedicao',
        ),
    ]
