# Generated by Django 5.0.1 on 2024-02-05 12:51


from django.db import migrations, models
import django.utils.timezone



class Migration(migrations.Migration):

    dependencies = [
        ('aaaa', '0006_medicaovelocidade_delete_dispositivomedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='manutencao',
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
    ]