# Generated by Django 5.0.1 on 2024-02-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaaa', '0006_medicaovelocidade_delete_dispositivomedicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='manutencao',
            field=models.DateField(auto_now_add=True, default=0.0004940711462450593),
            preserve_default=False,
        ),
    ]
