# Generated by Django 5.0.1 on 2024-02-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aaaa', '0007_produto_manutencao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='manutencao',
        ),
    ]
