# Generated by Django 5.0.1 on 2024-02-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aaaa', '0009_medicaovelocidade_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaovelocidade',
            name='dispositivo_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
